# debug
DEBUG = True

# database
MONGODB_CONNECTION = 'mongodb'
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017

CONNECTION = '{}://{}:{}'.format(MONGODB_CONNECTION, MONGODB_HOST, MONGODB_PORT)
MONGODB_DATABASE = 'ironcoins'

